### ISSUE TITLE
Lyvi won't start

### ISSUE THREAD

**Issue by astralspurs** [ok100/lyvi#53]
Launching lyvi now results in this series of tracebacks. I'm not sure how to remedy this. I have little experience with python, and if I need to download the 'plyr' distribution, I'm not sure where to look. Any help would be apreciated.

`
Traceback (most recent call last):
  File "/usr/bin/lyvi", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'plyr' distribution was not found and is required by Lyvi
`

Some system info:
`Linux ArchLinux 4.14.65-1-lts #1 SMP Sat Aug 18 12:17:05 CEST 2018 x86_64 GNU/Linux`

Thank you.

**Comment by SicariusNoctis** [comment]
The PKGBUILD dependencies are all messed up for the various packages. Here's a quick 'n dirty fix:

    aurman -R lyvi-git glyr-git python-glyr-git
    aurman -S  lyvi python-glyr

**Comment by astralspurs** [comment]
Thanks SicariusNoctis!
